"""Model artifact error codes."""

from __future__ import annotations

from enum import StrEnum


class ModelErrorCode(StrEnum):
    ARTIFACT_NOT_FOUND = "MODEL_ARTIFACT_NOT_FOUND"
    CHECKSUM_MISMATCH = "MODEL_CHECKSUM_MISMATCH"
    SCHEMA_INCOMPATIBLE = "MODEL_SCHEMA_INCOMPATIBLE"
    APPROVAL_REJECTED = "MODEL_APPROVAL_REJECTED"
    LOAD_FAILED = "MODEL_LOAD_FAILED"
    INFERENCE_FAILED = "MODEL_INFERENCE_FAILED"
    MANIFEST_INVALID = "MODEL_MANIFEST_INVALID"
