"""Scenario SDK validation error codes."""

from __future__ import annotations

from enum import StrEnum


class ScenarioErrorCode(StrEnum):
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
    DUPLICATE_ID = "DUPLICATE_ID"
    DANGLING_REFERENCE = "DANGLING_REFERENCE"
    UNKNOWN_PLUGIN = "UNKNOWN_PLUGIN"
    INVALID_PLUGIN_CONFIG = "INVALID_PLUGIN_CONFIG"
    INVALID_BRANCH_WEIGHT = "INVALID_BRANCH_WEIGHT"
    PLATFORM_VERSION_INCOMPATIBLE = "PLATFORM_VERSION_INCOMPATIBLE"
    CHECKSUM_MISMATCH = "CHECKSUM_MISMATCH"
    UNSAFE_CONTENT = "UNSAFE_CONTENT"
    PACKAGE_LAYOUT_INVALID = "PACKAGE_LAYOUT_INVALID"
    PUBLICATION_CONFLICT = "PUBLICATION_CONFLICT"
    VALIDATION_FAILED = "VALIDATION_FAILED"
