packages:
  - 'apps/*'
  - 'packages/*'

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
blockExoticSubdeps: true
trustLockfile: false
strictDepBuilds: true
dangerouslyAllowAllBuilds: false
engineStrict: true
strictPeerDependencies: true

allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true
  unrs-resolver: true
