export const WORKSPACE_VERSION = '0.0.0-phase08' as const;

export const PROTOCOL_VERSION_V1 = 1;

export const DOMAIN_EVENT_SCHEMA_VERSION = 1;
export const GRAPH_NODE_SCHEMA_VERSION = 1;
export const GRAPH_EDGE_SCHEMA_VERSION = 1;
export const GRAPH_SNAPSHOT_SCHEMA_VERSION = 1;
export const GRAPH_DELTA_SCHEMA_VERSION = 1;
export const GRAPH_PATH_QUERY_SCHEMA_VERSION = 1;
export const GRAPH_PATH_RESULT_SCHEMA_VERSION = 1;
export const API_ERROR_SCHEMA_VERSION = 1;
export const CURSOR_PAGINATION_SCHEMA_VERSION = 1;
export const IDEMPOTENCY_SCHEMA_VERSION = 1;
export const IDEMPOTENCY_RECORD_SCHEMA_VERSION = 1;
export const OBJECT_METADATA_REFERENCE_SCHEMA_VERSION = 1;
export const SCENARIO_SCHEMA_VERSION = 1;
export const SCENARIO_VERSION_SCHEMA_VERSION = 1;
export const RUN_SCHEMA_VERSION = 1;
export const ALERT_SCHEMA_VERSION = 1;
export const INCIDENT_SCHEMA_VERSION = 1;
export const EVIDENCE_SCHEMA_VERSION = 1;
export const HYPOTHESIS_SCHEMA_VERSION = 1;
export const AGENT_SESSION_SCHEMA_VERSION = 1;
export const ACTION_PROPOSAL_SCHEMA_VERSION = 1;
export const APPROVAL_SCHEMA_VERSION = 1;
export const EXECUTED_ACTION_SCHEMA_VERSION = 1;
export const MODEL_MANIFEST_SCHEMA_VERSION = 1;
export const MODEL_SCORE_SCHEMA_VERSION = 1;

export const SUPPORTED_SCHEMA_VERSIONS: Readonly<Record<string, readonly number[]>> = {
  domain_event: [DOMAIN_EVENT_SCHEMA_VERSION],
  graph_node: [GRAPH_NODE_SCHEMA_VERSION],
  graph_edge: [GRAPH_EDGE_SCHEMA_VERSION],
  graph_snapshot: [GRAPH_SNAPSHOT_SCHEMA_VERSION],
  graph_delta: [GRAPH_DELTA_SCHEMA_VERSION],
  graph_path_query: [GRAPH_PATH_QUERY_SCHEMA_VERSION],
  graph_path_result: [GRAPH_PATH_RESULT_SCHEMA_VERSION],
  api_error: [API_ERROR_SCHEMA_VERSION],
  cursor_pagination: [CURSOR_PAGINATION_SCHEMA_VERSION],
  idempotency: [IDEMPOTENCY_SCHEMA_VERSION],
  idempotency_record: [IDEMPOTENCY_RECORD_SCHEMA_VERSION],
  object_metadata_reference: [OBJECT_METADATA_REFERENCE_SCHEMA_VERSION],
  scenario: [SCENARIO_SCHEMA_VERSION],
  scenario_version: [SCENARIO_VERSION_SCHEMA_VERSION],
  run: [RUN_SCHEMA_VERSION],
  alert: [ALERT_SCHEMA_VERSION],
  incident: [INCIDENT_SCHEMA_VERSION],
  evidence: [EVIDENCE_SCHEMA_VERSION],
  hypothesis: [HYPOTHESIS_SCHEMA_VERSION],
  agent_session: [AGENT_SESSION_SCHEMA_VERSION],
  action_proposal: [ACTION_PROPOSAL_SCHEMA_VERSION],
  approval: [APPROVAL_SCHEMA_VERSION],
  executed_action: [EXECUTED_ACTION_SCHEMA_VERSION],
  model_manifest: [MODEL_MANIFEST_SCHEMA_VERSION],
  model_score: [MODEL_SCORE_SCHEMA_VERSION],
};
