export const WORKSPACE_VERSION = '0.0.0-phase23' as const;

export const PROTOCOL_VERSION_V1 = 1;

export const DOMAIN_EVENT_SCHEMA_VERSION = 1;
export const GRAPH_NODE_SCHEMA_VERSION = 1;
export const GRAPH_EDGE_SCHEMA_VERSION = 1;
export const GRAPH_SNAPSHOT_SCHEMA_VERSION = 1;
export const GRAPH_DELTA_SCHEMA_VERSION = 1;
export const GRAPH_PATH_QUERY_SCHEMA_VERSION = 1;
export const GRAPH_PATH_RESULT_SCHEMA_VERSION = 1;
export const API_ERROR_SCHEMA_VERSION = 1;
export const CURSOR_PAGINATION_SCHEMA_VERSION = 1;
export const IDEMPOTENCY_SCHEMA_VERSION = 1;
export const IDEMPOTENCY_RECORD_SCHEMA_VERSION = 1;
export const OBJECT_METADATA_REFERENCE_SCHEMA_VERSION = 1;
export const SCENARIO_SCHEMA_VERSION = 1;
export const SCENARIO_VERSION_SCHEMA_VERSION = 1;
export const RUN_SCHEMA_VERSION = 1;
export const ALERT_SCHEMA_VERSION = 1;
export const INCIDENT_SCHEMA_VERSION = 1;
export const EVIDENCE_SCHEMA_VERSION = 1;
export const HYPOTHESIS_SCHEMA_VERSION = 2;
export const AGENT_SESSION_SCHEMA_VERSION = 1;
export const ACTION_PROPOSAL_SCHEMA_VERSION = 2;
export const APPROVAL_SCHEMA_VERSION = 1;
export const EXECUTED_ACTION_SCHEMA_VERSION = 1;
export const MODEL_MANIFEST_SCHEMA_VERSION = 1;
export const MODEL_SCORE_SCHEMA_VERSION = 1;
export const RUN_CONFIGURATION_SCHEMA_VERSION = 1;
export const SCHEDULED_EVENT_SCHEMA_VERSION = 1;
export const SIMULATION_COMMAND_SCHEMA_VERSION = 1;
export const SIMULATION_CHECKPOINT_SCHEMA_VERSION = 1;
export const WORLD_STATE_SNAPSHOT_SCHEMA_VERSION = 1;
export const NORMALIZED_EVENT_HASH_SCHEMA_VERSION = 1;
export const REALTIME_MESSAGE_SCHEMA_VERSION = 1;
export const CONSUMER_CURSOR_SCHEMA_VERSION = 1;
export const DEAD_LETTER_RECORD_SCHEMA_VERSION = 1;
export const BACKFILL_REQUEST_SCHEMA_VERSION = 1;
export const BACKFILL_RESULT_SCHEMA_VERSION = 1;
export const WEBSOCKET_FRAME_SCHEMA_VERSION = 1;
export const LIVE_RUN_SCHEMA_VERSION = 1;
export const TIMELINE_ENTRY_SCHEMA_VERSION = 1;
export const SNAPSHOT_BOOTSTRAP_SCHEMA_VERSION = 1;
export const RUN_CREATE_REQUEST_SCHEMA_VERSION = 1;
export const RUN_COMMAND_RESPONSE_SCHEMA_VERSION = 1;
export const CONNECTION_HEALTH_SCHEMA_VERSION = 1;
export const REALTIME_REDUCER_ACTION_SCHEMA_VERSION = 1;
export const FEATURE_SCHEMA_MANIFEST_SCHEMA_VERSION = 1;
export const FEATURE_VECTOR_SCHEMA_VERSION = 1;
export const FEATURE_WINDOW_SCHEMA_VERSION = 1;
export const FEATURE_PROVENANCE_SCHEMA_VERSION = 1;
export const DATASET_MANIFEST_SCHEMA_VERSION = 1;
export const ONLINE_FEATURE_UPDATE_SCHEMA_VERSION = 1;
export const FEATURE_COMPUTE_REQUEST_SCHEMA_VERSION = 1;
export const FEATURE_COMPUTE_RESPONSE_SCHEMA_VERSION = 1;
export const FEATURE_PARITY_CHECK_RESPONSE_SCHEMA_VERSION = 1;
export const FEATURE_SCHEMA_VERSION = 1;
export const DETECTION_RULE_SCHEMA_VERSION = 1;
export const DETECTION_RULE_REGISTRY_SCHEMA_VERSION = 1;
export const RULE_THRESHOLD_SCHEMA_VERSION = 1;
export const STATISTICAL_BASELINE_SCHEMA_VERSION = 1;
export const STATISTICAL_BASELINE_MANIFEST_SCHEMA_VERSION = 1;
export const RULE_EXPLANATION_SCHEMA_VERSION = 1;
export const ALERT_CANDIDATE_SCHEMA_VERSION = 1;
export const RULE_EVALUATION_SCHEMA_VERSION = 1;
export const METRIC_REPORT_SCHEMA_VERSION = 1;
export const EVALUATION_RUN_SCHEMA_VERSION = 1;
export const DETECTION_EVALUATE_REQUEST_SCHEMA_VERSION = 1;
export const DETECTION_EVALUATE_RESPONSE_SCHEMA_VERSION = 1;
export const ANOMALY_EXPLANATION_SCHEMA_VERSION = 1;
export const MODEL_ARTIFACT_REFERENCE_SCHEMA_VERSION = 1;
export const TRAINING_RUN_MANIFEST_SCHEMA_VERSION = 1;
export const MODEL_INFERENCE_RESULT_SCHEMA_VERSION = 1;
export const MODEL_EVALUATE_REQUEST_SCHEMA_VERSION = 1;
export const MODEL_EVALUATE_RESPONSE_SCHEMA_VERSION = 1;
export const MODEL_VERIFY_ARTIFACT_REQUEST_SCHEMA_VERSION = 1;
export const MODEL_VERIFY_ARTIFACT_RESPONSE_SCHEMA_VERSION = 1;
export const RISK_INPUT_SCHEMA_VERSION = 1;
export const RISK_ENGINE_CONFIG_SCHEMA_VERSION = 1;
export const RISK_EXPLANATION_PATH_SCHEMA_VERSION = 1;
export const RISK_CONTRIBUTION_SCHEMA_VERSION = 1;
export const ASSET_RISK_SCORE_SCHEMA_VERSION = 1;
export const RISK_PROJECTION_DELTA_SCHEMA_VERSION = 1;
export const RISK_COMPUTE_REQUEST_SCHEMA_VERSION = 1;
export const RISK_COMPUTE_RESPONSE_SCHEMA_VERSION = 1;
export const RISK_SCORES_LIST_RESPONSE_SCHEMA_VERSION = 1;
export const GENERATION_REQUEST_SCHEMA_VERSION = 1;
export const GENERATION_RESPONSE_SCHEMA_VERSION = 1;
export const STRUCTURED_OUTPUT_SPEC_SCHEMA_VERSION = 1;
export const TOOL_SCHEMA_SCHEMA_VERSION = 1;
export const PROVIDER_CAPABILITIES_SCHEMA_VERSION = 1;
export const MODEL_CONFIG_SCHEMA_VERSION = 1;
export const PROVIDER_USAGE_SCHEMA_VERSION = 1;
export const PROVIDER_ERROR_SCHEMA_VERSION = 1;
export const RECORDED_RESPONSE_KEY_SCHEMA_VERSION = 1;
export const GENERATION_ARTIFACT_SCHEMA_VERSION = 1;
export const PROVIDER_GENERATE_REQUEST_SCHEMA_VERSION = 1;
export const PROVIDER_GENERATE_RESPONSE_SCHEMA_VERSION = 1;
export const AGENT_DEFINITION_SCHEMA_VERSION = 1;
export const AGENT_TASK_SCHEMA_VERSION = 1;
export const AGENT_STATE_TRANSITION_SCHEMA_VERSION = 1;
export const TOOL_DEFINITION_SCHEMA_VERSION = 1;
export const TOOL_INVOCATION_SCHEMA_VERSION = 1;
export const TOOL_RESULT_SCHEMA_VERSION = 1;
export const EVIDENCE_CITATION_SCHEMA_VERSION = 1;
export const AGENT_BUDGET_SCHEMA_VERSION = 1;
export const AGENT_ARTIFACT_SCHEMA_VERSION = 1;
export const CREATE_AGENT_SESSION_REQUEST_SCHEMA_VERSION = 1;
export const CREATE_AGENT_TASK_REQUEST_SCHEMA_VERSION = 1;
export const AGENT_SESSION_DETAIL_SCHEMA_VERSION = 1;
export const WATCHTOWER_TRIAGE_RESULT_SCHEMA_VERSION = 1;
export const TRACE_INVESTIGATION_PLAN_SCHEMA_VERSION = 1;
export const EVIDENCE_ATTACHMENT_SCHEMA_VERSION = 1;
export const CANDIDATE_AFFECTED_ASSET_SCHEMA_VERSION = 1;
export const INVESTIGATION_NOTE_SCHEMA_VERSION = 1;
export const AGENT_GRAPH_OVERLAY_SCHEMA_VERSION = 1;
export const INVESTIGATION_DETAIL_SCHEMA_VERSION = 3;
export const TRIGGER_WATCHTOWER_REQUEST_SCHEMA_VERSION = 1;
export const HYPOTHESIS_CLAIM_SCHEMA_VERSION = 1;
export const CONFIDENCE_ASSESSMENT_SCHEMA_VERSION = 1;
export const CONTRADICTION_LINK_SCHEMA_VERSION = 1;
export const HYPOTHESIS_REVISION_SCHEMA_VERSION = 1;
export const HYPOTHESIS_COMPARISON_SCHEMA_VERSION = 1;
export const VERIFICATION_REQUEST_SCHEMA_VERSION = 1;
export const TRIGGER_ORACLE_REQUEST_SCHEMA_VERSION = 1;
export const RESPONSE_OPTION_SCHEMA_VERSION = 1;
export const PROPOSAL_REVISION_SCHEMA_VERSION = 1;
export const POLICY_INPUT_SCHEMA_VERSION = 1;
export const POLICY_DECISION_SCHEMA_VERSION = 1;
export const APPROVAL_REQUIREMENT_SCHEMA_VERSION = 1;
export const TRIGGER_BASTION_REQUEST_SCHEMA_VERSION = 1;
export const TRIGGER_WARDEN_REQUEST_SCHEMA_VERSION = 1;
export const REPORT_CITATION_SCHEMA_VERSION = 1;
export const REPORT_CLAIM_SCHEMA_VERSION = 1;
export const REPORT_TIMELINE_ENTRY_SCHEMA_VERSION = 1;
export const AFTER_ACTION_REPORT_SOURCE_SCHEMA_VERSION = 1;
export const AFTER_ACTION_REPORT_SCHEMA_VERSION = 1;
export const REPORT_VERSION_SCHEMA_VERSION = 1;
export const REPORT_EXPORT_ARTIFACT_SCHEMA_VERSION = 1;
export const GROUNDING_VALIDATION_RESULT_SCHEMA_VERSION = 1;
export const TRIGGER_SCRIBE_REQUEST_SCHEMA_VERSION = 1;

export const SUPPORTED_SCHEMA_VERSIONS: Readonly<Record<string, readonly number[]>> = {
  domain_event: [DOMAIN_EVENT_SCHEMA_VERSION],
  graph_node: [GRAPH_NODE_SCHEMA_VERSION],
  graph_edge: [GRAPH_EDGE_SCHEMA_VERSION],
  graph_snapshot: [GRAPH_SNAPSHOT_SCHEMA_VERSION],
  graph_delta: [GRAPH_DELTA_SCHEMA_VERSION],
  graph_path_query: [GRAPH_PATH_QUERY_SCHEMA_VERSION],
  graph_path_result: [GRAPH_PATH_RESULT_SCHEMA_VERSION],
  api_error: [API_ERROR_SCHEMA_VERSION],
  cursor_pagination: [CURSOR_PAGINATION_SCHEMA_VERSION],
  idempotency: [IDEMPOTENCY_SCHEMA_VERSION],
  idempotency_record: [IDEMPOTENCY_RECORD_SCHEMA_VERSION],
  object_metadata_reference: [OBJECT_METADATA_REFERENCE_SCHEMA_VERSION],
  scenario: [SCENARIO_SCHEMA_VERSION],
  scenario_version: [SCENARIO_VERSION_SCHEMA_VERSION],
  run: [RUN_SCHEMA_VERSION],
  alert: [ALERT_SCHEMA_VERSION],
  incident: [INCIDENT_SCHEMA_VERSION],
  evidence: [EVIDENCE_SCHEMA_VERSION],
  hypothesis: [1, HYPOTHESIS_SCHEMA_VERSION],
  hypothesis_claim: [HYPOTHESIS_CLAIM_SCHEMA_VERSION],
  confidence_assessment: [CONFIDENCE_ASSESSMENT_SCHEMA_VERSION],
  contradiction_link: [CONTRADICTION_LINK_SCHEMA_VERSION],
  hypothesis_revision: [HYPOTHESIS_REVISION_SCHEMA_VERSION],
  hypothesis_comparison: [HYPOTHESIS_COMPARISON_SCHEMA_VERSION],
  verification_request: [VERIFICATION_REQUEST_SCHEMA_VERSION],
  trigger_oracle_request: [TRIGGER_ORACLE_REQUEST_SCHEMA_VERSION],
  agent_session: [AGENT_SESSION_SCHEMA_VERSION],
  action_proposal: [1, ACTION_PROPOSAL_SCHEMA_VERSION],
  response_option: [RESPONSE_OPTION_SCHEMA_VERSION],
  proposal_revision: [PROPOSAL_REVISION_SCHEMA_VERSION],
  policy_input: [POLICY_INPUT_SCHEMA_VERSION],
  policy_decision: [POLICY_DECISION_SCHEMA_VERSION],
  approval_requirement: [APPROVAL_REQUIREMENT_SCHEMA_VERSION],
  trigger_bastion_request: [TRIGGER_BASTION_REQUEST_SCHEMA_VERSION],
  trigger_warden_request: [TRIGGER_WARDEN_REQUEST_SCHEMA_VERSION],
  report_citation: [REPORT_CITATION_SCHEMA_VERSION],
  report_claim: [REPORT_CLAIM_SCHEMA_VERSION],
  report_timeline_entry: [REPORT_TIMELINE_ENTRY_SCHEMA_VERSION],
  after_action_report_source: [AFTER_ACTION_REPORT_SOURCE_SCHEMA_VERSION],
  after_action_report: [AFTER_ACTION_REPORT_SCHEMA_VERSION],
  report_version: [REPORT_VERSION_SCHEMA_VERSION],
  report_export_artifact: [REPORT_EXPORT_ARTIFACT_SCHEMA_VERSION],
  grounding_validation_result: [GROUNDING_VALIDATION_RESULT_SCHEMA_VERSION],
  trigger_scribe_request: [TRIGGER_SCRIBE_REQUEST_SCHEMA_VERSION],
  approval: [APPROVAL_SCHEMA_VERSION],
  executed_action: [EXECUTED_ACTION_SCHEMA_VERSION],
  model_manifest: [MODEL_MANIFEST_SCHEMA_VERSION],
  model_score: [MODEL_SCORE_SCHEMA_VERSION],
  run_configuration: [RUN_CONFIGURATION_SCHEMA_VERSION],
  scheduled_event: [SCHEDULED_EVENT_SCHEMA_VERSION],
  simulation_command: [SIMULATION_COMMAND_SCHEMA_VERSION],
  simulation_checkpoint: [SIMULATION_CHECKPOINT_SCHEMA_VERSION],
  world_state_snapshot: [WORLD_STATE_SNAPSHOT_SCHEMA_VERSION],
  normalized_event_hash: [NORMALIZED_EVENT_HASH_SCHEMA_VERSION],
  realtime_message: [REALTIME_MESSAGE_SCHEMA_VERSION],
  consumer_cursor: [CONSUMER_CURSOR_SCHEMA_VERSION],
  dead_letter_record: [DEAD_LETTER_RECORD_SCHEMA_VERSION],
  backfill_request: [BACKFILL_REQUEST_SCHEMA_VERSION],
  backfill_result: [BACKFILL_RESULT_SCHEMA_VERSION],
  websocket_frame: [WEBSOCKET_FRAME_SCHEMA_VERSION],
  live_run: [LIVE_RUN_SCHEMA_VERSION],
  timeline_entry: [TIMELINE_ENTRY_SCHEMA_VERSION],
  snapshot_bootstrap: [SNAPSHOT_BOOTSTRAP_SCHEMA_VERSION],
  run_create_request: [RUN_CREATE_REQUEST_SCHEMA_VERSION],
  run_command_response: [RUN_COMMAND_RESPONSE_SCHEMA_VERSION],
  connection_health: [CONNECTION_HEALTH_SCHEMA_VERSION],
  feature_schema_manifest: [FEATURE_SCHEMA_MANIFEST_SCHEMA_VERSION],
  feature_vector: [FEATURE_VECTOR_SCHEMA_VERSION],
  feature_window: [FEATURE_WINDOW_SCHEMA_VERSION],
  feature_provenance: [FEATURE_PROVENANCE_SCHEMA_VERSION],
  dataset_manifest: [DATASET_MANIFEST_SCHEMA_VERSION],
  online_feature_update: [ONLINE_FEATURE_UPDATE_SCHEMA_VERSION],
  detection_rule: [DETECTION_RULE_SCHEMA_VERSION],
  detection_rule_registry: [DETECTION_RULE_REGISTRY_SCHEMA_VERSION],
  rule_threshold: [RULE_THRESHOLD_SCHEMA_VERSION],
  statistical_baseline: [STATISTICAL_BASELINE_SCHEMA_VERSION],
  statistical_baseline_manifest: [STATISTICAL_BASELINE_MANIFEST_SCHEMA_VERSION],
  rule_explanation: [RULE_EXPLANATION_SCHEMA_VERSION],
  alert_candidate: [ALERT_CANDIDATE_SCHEMA_VERSION],
  rule_evaluation: [RULE_EVALUATION_SCHEMA_VERSION],
  metric_report: [METRIC_REPORT_SCHEMA_VERSION],
  evaluation_run: [EVALUATION_RUN_SCHEMA_VERSION],
  detection_evaluate_request: [DETECTION_EVALUATE_REQUEST_SCHEMA_VERSION],
  detection_evaluate_response: [DETECTION_EVALUATE_RESPONSE_SCHEMA_VERSION],
  anomaly_explanation: [ANOMALY_EXPLANATION_SCHEMA_VERSION],
  model_artifact_reference: [MODEL_ARTIFACT_REFERENCE_SCHEMA_VERSION],
  training_run_manifest: [TRAINING_RUN_MANIFEST_SCHEMA_VERSION],
  model_inference_result: [MODEL_INFERENCE_RESULT_SCHEMA_VERSION],
  model_evaluate_request: [MODEL_EVALUATE_REQUEST_SCHEMA_VERSION],
  model_evaluate_response: [MODEL_EVALUATE_RESPONSE_SCHEMA_VERSION],
  model_verify_artifact_request: [MODEL_VERIFY_ARTIFACT_REQUEST_SCHEMA_VERSION],
  model_verify_artifact_response: [MODEL_VERIFY_ARTIFACT_RESPONSE_SCHEMA_VERSION],
  risk_input: [RISK_INPUT_SCHEMA_VERSION],
  risk_engine_config: [RISK_ENGINE_CONFIG_SCHEMA_VERSION],
  risk_explanation_path: [RISK_EXPLANATION_PATH_SCHEMA_VERSION],
  risk_contribution: [RISK_CONTRIBUTION_SCHEMA_VERSION],
  asset_risk_score: [ASSET_RISK_SCORE_SCHEMA_VERSION],
  risk_projection_delta: [RISK_PROJECTION_DELTA_SCHEMA_VERSION],
  risk_compute_request: [RISK_COMPUTE_REQUEST_SCHEMA_VERSION],
  risk_compute_response: [RISK_COMPUTE_RESPONSE_SCHEMA_VERSION],
  risk_scores_list_response: [RISK_SCORES_LIST_RESPONSE_SCHEMA_VERSION],
  generation_request: [GENERATION_REQUEST_SCHEMA_VERSION],
  generation_response: [GENERATION_RESPONSE_SCHEMA_VERSION],
  structured_output_spec: [STRUCTURED_OUTPUT_SPEC_SCHEMA_VERSION],
  tool_schema: [TOOL_SCHEMA_SCHEMA_VERSION],
  provider_capabilities: [PROVIDER_CAPABILITIES_SCHEMA_VERSION],
  model_config: [MODEL_CONFIG_SCHEMA_VERSION],
  provider_usage: [PROVIDER_USAGE_SCHEMA_VERSION],
  provider_error: [PROVIDER_ERROR_SCHEMA_VERSION],
  recorded_response_key: [RECORDED_RESPONSE_KEY_SCHEMA_VERSION],
  generation_artifact: [GENERATION_ARTIFACT_SCHEMA_VERSION],
  provider_generate_request: [PROVIDER_GENERATE_REQUEST_SCHEMA_VERSION],
  provider_generate_response: [PROVIDER_GENERATE_RESPONSE_SCHEMA_VERSION],
  agent_definition: [AGENT_DEFINITION_SCHEMA_VERSION],
  agent_task: [AGENT_TASK_SCHEMA_VERSION],
  agent_state_transition: [AGENT_STATE_TRANSITION_SCHEMA_VERSION],
  tool_definition: [TOOL_DEFINITION_SCHEMA_VERSION],
  tool_invocation: [TOOL_INVOCATION_SCHEMA_VERSION],
  tool_result: [TOOL_RESULT_SCHEMA_VERSION],
  evidence_citation: [EVIDENCE_CITATION_SCHEMA_VERSION],
  agent_budget: [AGENT_BUDGET_SCHEMA_VERSION],
  agent_artifact: [AGENT_ARTIFACT_SCHEMA_VERSION],
  create_agent_session_request: [CREATE_AGENT_SESSION_REQUEST_SCHEMA_VERSION],
  create_agent_task_request: [CREATE_AGENT_TASK_REQUEST_SCHEMA_VERSION],
  agent_session_detail: [AGENT_SESSION_DETAIL_SCHEMA_VERSION],
  watchtower_triage_result: [WATCHTOWER_TRIAGE_RESULT_SCHEMA_VERSION],
  trace_investigation_plan: [TRACE_INVESTIGATION_PLAN_SCHEMA_VERSION],
  evidence_attachment: [EVIDENCE_ATTACHMENT_SCHEMA_VERSION],
  candidate_affected_asset: [CANDIDATE_AFFECTED_ASSET_SCHEMA_VERSION],
  investigation_note: [INVESTIGATION_NOTE_SCHEMA_VERSION],
  agent_graph_overlay: [AGENT_GRAPH_OVERLAY_SCHEMA_VERSION],
  investigation_detail: [1, 2, INVESTIGATION_DETAIL_SCHEMA_VERSION],
};
