export const WORKSPACE_VERSION = '0.0.0-phase14' as const;

export const PROTOCOL_VERSION_V1 = 1;

export const DOMAIN_EVENT_SCHEMA_VERSION = 1;
export const GRAPH_NODE_SCHEMA_VERSION = 1;
export const GRAPH_EDGE_SCHEMA_VERSION = 1;
export const GRAPH_SNAPSHOT_SCHEMA_VERSION = 1;
export const GRAPH_DELTA_SCHEMA_VERSION = 1;
export const GRAPH_PATH_QUERY_SCHEMA_VERSION = 1;
export const GRAPH_PATH_RESULT_SCHEMA_VERSION = 1;
export const API_ERROR_SCHEMA_VERSION = 1;
export const CURSOR_PAGINATION_SCHEMA_VERSION = 1;
export const IDEMPOTENCY_SCHEMA_VERSION = 1;
export const IDEMPOTENCY_RECORD_SCHEMA_VERSION = 1;
export const OBJECT_METADATA_REFERENCE_SCHEMA_VERSION = 1;
export const SCENARIO_SCHEMA_VERSION = 1;
export const SCENARIO_VERSION_SCHEMA_VERSION = 1;
export const RUN_SCHEMA_VERSION = 1;
export const ALERT_SCHEMA_VERSION = 1;
export const INCIDENT_SCHEMA_VERSION = 1;
export const EVIDENCE_SCHEMA_VERSION = 1;
export const HYPOTHESIS_SCHEMA_VERSION = 1;
export const AGENT_SESSION_SCHEMA_VERSION = 1;
export const ACTION_PROPOSAL_SCHEMA_VERSION = 1;
export const APPROVAL_SCHEMA_VERSION = 1;
export const EXECUTED_ACTION_SCHEMA_VERSION = 1;
export const MODEL_MANIFEST_SCHEMA_VERSION = 1;
export const MODEL_SCORE_SCHEMA_VERSION = 1;
export const RUN_CONFIGURATION_SCHEMA_VERSION = 1;
export const SCHEDULED_EVENT_SCHEMA_VERSION = 1;
export const SIMULATION_COMMAND_SCHEMA_VERSION = 1;
export const SIMULATION_CHECKPOINT_SCHEMA_VERSION = 1;
export const WORLD_STATE_SNAPSHOT_SCHEMA_VERSION = 1;
export const NORMALIZED_EVENT_HASH_SCHEMA_VERSION = 1;
export const REALTIME_MESSAGE_SCHEMA_VERSION = 1;
export const CONSUMER_CURSOR_SCHEMA_VERSION = 1;
export const DEAD_LETTER_RECORD_SCHEMA_VERSION = 1;
export const BACKFILL_REQUEST_SCHEMA_VERSION = 1;
export const BACKFILL_RESULT_SCHEMA_VERSION = 1;
export const WEBSOCKET_FRAME_SCHEMA_VERSION = 1;
export const LIVE_RUN_SCHEMA_VERSION = 1;
export const TIMELINE_ENTRY_SCHEMA_VERSION = 1;
export const SNAPSHOT_BOOTSTRAP_SCHEMA_VERSION = 1;
export const RUN_CREATE_REQUEST_SCHEMA_VERSION = 1;
export const RUN_COMMAND_RESPONSE_SCHEMA_VERSION = 1;
export const CONNECTION_HEALTH_SCHEMA_VERSION = 1;
export const REALTIME_REDUCER_ACTION_SCHEMA_VERSION = 1;
export const FEATURE_SCHEMA_MANIFEST_SCHEMA_VERSION = 1;
export const FEATURE_VECTOR_SCHEMA_VERSION = 1;
export const FEATURE_WINDOW_SCHEMA_VERSION = 1;
export const FEATURE_PROVENANCE_SCHEMA_VERSION = 1;
export const DATASET_MANIFEST_SCHEMA_VERSION = 1;
export const ONLINE_FEATURE_UPDATE_SCHEMA_VERSION = 1;
export const FEATURE_COMPUTE_REQUEST_SCHEMA_VERSION = 1;
export const FEATURE_COMPUTE_RESPONSE_SCHEMA_VERSION = 1;
export const FEATURE_PARITY_CHECK_RESPONSE_SCHEMA_VERSION = 1;
export const FEATURE_SCHEMA_VERSION = 1;

export const SUPPORTED_SCHEMA_VERSIONS: Readonly<Record<string, readonly number[]>> = {
  domain_event: [DOMAIN_EVENT_SCHEMA_VERSION],
  graph_node: [GRAPH_NODE_SCHEMA_VERSION],
  graph_edge: [GRAPH_EDGE_SCHEMA_VERSION],
  graph_snapshot: [GRAPH_SNAPSHOT_SCHEMA_VERSION],
  graph_delta: [GRAPH_DELTA_SCHEMA_VERSION],
  graph_path_query: [GRAPH_PATH_QUERY_SCHEMA_VERSION],
  graph_path_result: [GRAPH_PATH_RESULT_SCHEMA_VERSION],
  api_error: [API_ERROR_SCHEMA_VERSION],
  cursor_pagination: [CURSOR_PAGINATION_SCHEMA_VERSION],
  idempotency: [IDEMPOTENCY_SCHEMA_VERSION],
  idempotency_record: [IDEMPOTENCY_RECORD_SCHEMA_VERSION],
  object_metadata_reference: [OBJECT_METADATA_REFERENCE_SCHEMA_VERSION],
  scenario: [SCENARIO_SCHEMA_VERSION],
  scenario_version: [SCENARIO_VERSION_SCHEMA_VERSION],
  run: [RUN_SCHEMA_VERSION],
  alert: [ALERT_SCHEMA_VERSION],
  incident: [INCIDENT_SCHEMA_VERSION],
  evidence: [EVIDENCE_SCHEMA_VERSION],
  hypothesis: [HYPOTHESIS_SCHEMA_VERSION],
  agent_session: [AGENT_SESSION_SCHEMA_VERSION],
  action_proposal: [ACTION_PROPOSAL_SCHEMA_VERSION],
  approval: [APPROVAL_SCHEMA_VERSION],
  executed_action: [EXECUTED_ACTION_SCHEMA_VERSION],
  model_manifest: [MODEL_MANIFEST_SCHEMA_VERSION],
  model_score: [MODEL_SCORE_SCHEMA_VERSION],
  run_configuration: [RUN_CONFIGURATION_SCHEMA_VERSION],
  scheduled_event: [SCHEDULED_EVENT_SCHEMA_VERSION],
  simulation_command: [SIMULATION_COMMAND_SCHEMA_VERSION],
  simulation_checkpoint: [SIMULATION_CHECKPOINT_SCHEMA_VERSION],
  world_state_snapshot: [WORLD_STATE_SNAPSHOT_SCHEMA_VERSION],
  normalized_event_hash: [NORMALIZED_EVENT_HASH_SCHEMA_VERSION],
  realtime_message: [REALTIME_MESSAGE_SCHEMA_VERSION],
  consumer_cursor: [CONSUMER_CURSOR_SCHEMA_VERSION],
  dead_letter_record: [DEAD_LETTER_RECORD_SCHEMA_VERSION],
  backfill_request: [BACKFILL_REQUEST_SCHEMA_VERSION],
  backfill_result: [BACKFILL_RESULT_SCHEMA_VERSION],
  websocket_frame: [WEBSOCKET_FRAME_SCHEMA_VERSION],
  live_run: [LIVE_RUN_SCHEMA_VERSION],
  timeline_entry: [TIMELINE_ENTRY_SCHEMA_VERSION],
  snapshot_bootstrap: [SNAPSHOT_BOOTSTRAP_SCHEMA_VERSION],
  run_create_request: [RUN_CREATE_REQUEST_SCHEMA_VERSION],
  run_command_response: [RUN_COMMAND_RESPONSE_SCHEMA_VERSION],
  connection_health: [CONNECTION_HEALTH_SCHEMA_VERSION],
  feature_schema_manifest: [FEATURE_SCHEMA_MANIFEST_SCHEMA_VERSION],
  feature_vector: [FEATURE_VECTOR_SCHEMA_VERSION],
  feature_window: [FEATURE_WINDOW_SCHEMA_VERSION],
  feature_provenance: [FEATURE_PROVENANCE_SCHEMA_VERSION],
  dataset_manifest: [DATASET_MANIFEST_SCHEMA_VERSION],
  online_feature_update: [ONLINE_FEATURE_UPDATE_SCHEMA_VERSION],
};
