"""Fixture name to contract model mapping for cross-language tests."""

from __future__ import annotations

from pydantic import BaseModel

from aegis_contracts.agent_runtime import (
    AgentArtifactV1,
    AgentBudgetV1,
    AgentDefinitionV1,
    AgentSessionDetailV1,
    AgentStateTransitionV1,
    AgentTaskV1,
    CreateAgentSessionRequestV1,
    CreateAgentTaskRequestV1,
    EvidenceCitationV1,
    ToolDefinitionV1,
    ToolInvocationV1,
    ToolResultV1,
)
from aegis_contracts.api import CursorPaginationV1, IdempotencyMetadataV1
from aegis_contracts.entities import (
    ActionProposalV1,
    AgentSessionV1,
    AlertV1,
    ApprovalV1,
    EvidenceV1,
    ExecutedActionV1,
    HypothesisV1,
    IncidentV1,
    ModelManifestV1,
    ModelScoreV1,
    RunV1,
    ScenarioV1,
    ScenarioVersionV1,
)
from aegis_contracts.errors import ApiErrorEnvelopeV1
from aegis_contracts.events import DomainEventEnvelopeV1
from aegis_contracts.features import (
    DatasetManifestV1,
    FeatureComputeRequestV1,
    FeatureComputeResponseV1,
    FeatureParityCheckResponseV1,
    FeatureSchemaManifestV1,
    FeatureVectorV1,
    FeatureWindowV1,
    OnlineFeatureUpdateV1,
)
from aegis_contracts.generation import (
    GenerationArtifactV1,
    GenerationRequestV1,
    GenerationResponseV1,
    ModelConfigV1,
    ProviderCapabilitiesV1,
    ProviderErrorV1,
    ProviderGenerateRequestV1,
    ProviderGenerateResponseV1,
    ProviderUsageV1,
    RecordedResponseKeyV1,
    StructuredOutputSpecV1,
    ToolSchemaV1,
)
from aegis_contracts.graph import (
    GraphDeltaV1,
    GraphEdgeV1,
    GraphNodeV1,
    GraphPathQueryV1,
    GraphPathResultV1,
    GraphSnapshotV1,
)
from aegis_contracts.investigation import (
    AgentGraphOverlayV1,
    CandidateAffectedAssetV1,
    EvidenceAttachmentV1,
    InvestigationDetailV1,
    InvestigationNoteV1,
    TraceInvestigationPlanV1,
    WatchtowerTriageResultV1,
)
from aegis_contracts.live_run import (
    ConnectionHealthSnapshotV1,
    RunCommandResponseV1,
    RunCreateRequestV1,
    RunReplicatedState,
    SnapshotBootstrapPayloadV1,
    TimelineEntryV1,
)
from aegis_contracts.models import (
    AnomalyExplanationV1,
    ModelArtifactReferenceV1,
    ModelInferenceResultV1,
    ModelScoreRequestV1,
    ModelScoreResponseV1,
    ModelVerifyArtifactRequestV1,
    ModelVerifyArtifactResponseV1,
    TrainingRunManifestV1,
)
from aegis_contracts.persistence import IdempotencyRecordV1, ObjectMetadataReferenceV1
from aegis_contracts.realtime import (
    BackfillRequestV1,
    BackfillResultV1,
    ConsumerCursorV1,
    DeadLetterRecordV1,
    RealtimeMessageEnvelopeV1,
)
from aegis_contracts.risk import (
    AssetRiskScoreV1,
    RiskComputeRequestV1,
    RiskComputeResponseV1,
    RiskContributionV1,
    RiskEngineConfigV1,
    RiskExplanationPathV1,
    RiskInputV1,
    RiskProjectionDeltaV1,
    RiskScoresListResponseV1,
)
from aegis_contracts.simulation import (
    NormalizedEventHashV1,
    RunConfigurationV1,
    ScheduledEventV1,
    SimulationCheckpointV1,
    SimulationCommandV1,
    WorldStateSnapshotV1,
)
from aegis_contracts.websocket import WebSocketFrameV1

FIXTURE_MODEL_MAP: dict[str, type[BaseModel]] = {
    "event_envelope_v1": DomainEventEnvelopeV1,
    "graph_node_v1": GraphNodeV1,
    "graph_edge_v1": GraphEdgeV1,
    "graph_snapshot_v1": GraphSnapshotV1,
    "graph_delta_v1": GraphDeltaV1,
    "graph_path_query_v1": GraphPathQueryV1,
    "graph_path_result_v1": GraphPathResultV1,
    "api_error_v1": ApiErrorEnvelopeV1,
    "cursor_page_v1": CursorPaginationV1,
    "idempotency_v1": IdempotencyMetadataV1,
    "idempotency_record_v1": IdempotencyRecordV1,
    "object_metadata_reference_v1": ObjectMetadataReferenceV1,
    "scenario_v1": ScenarioV1,
    "scenario_version_v1": ScenarioVersionV1,
    "run_v1": RunV1,
    "alert_v1": AlertV1,
    "incident_v1": IncidentV1,
    "evidence_v1": EvidenceV1,
    "hypothesis_v1": HypothesisV1,
    "agent_session_v1": AgentSessionV1,
    "action_proposal_v1": ActionProposalV1,
    "approval_v1": ApprovalV1,
    "executed_action_v1": ExecutedActionV1,
    "model_manifest_v1": ModelManifestV1,
    "model_score_v1": ModelScoreV1,
    "run_configuration_v1": RunConfigurationV1,
    "scheduled_event_v1": ScheduledEventV1,
    "simulation_command_v1": SimulationCommandV1,
    "simulation_checkpoint_v1": SimulationCheckpointV1,
    "world_state_snapshot_v1": WorldStateSnapshotV1,
    "normalized_event_hash_v1": NormalizedEventHashV1,
    "realtime_message_envelope_v1": RealtimeMessageEnvelopeV1,
    "consumer_cursor_v1": ConsumerCursorV1,
    "dead_letter_record_v1": DeadLetterRecordV1,
    "backfill_request_v1": BackfillRequestV1,
    "backfill_result_v1": BackfillResultV1,
    "websocket_frame_v1": WebSocketFrameV1,
    "live_run_v1": RunReplicatedState,
    "timeline_entry_v1": TimelineEntryV1,
    "snapshot_bootstrap_v1": SnapshotBootstrapPayloadV1,
    "run_create_request_v1": RunCreateRequestV1,
    "run_command_response_v1": RunCommandResponseV1,
    "connection_health_v1": ConnectionHealthSnapshotV1,
    "feature_schema_manifest_v1": FeatureSchemaManifestV1,
    "feature_vector_v1": FeatureVectorV1,
    "feature_window_v1": FeatureWindowV1,
    "dataset_manifest_v1": DatasetManifestV1,
    "online_feature_update_v1": OnlineFeatureUpdateV1,
    "feature_compute_request_v1": FeatureComputeRequestV1,
    "feature_compute_response_v1": FeatureComputeResponseV1,
    "feature_parity_check_response_v1": FeatureParityCheckResponseV1,
    "anomaly_explanation_v1": AnomalyExplanationV1,
    "training_run_manifest_v1": TrainingRunManifestV1,
    "model_artifact_reference_v1": ModelArtifactReferenceV1,
    "model_inference_result_v1": ModelInferenceResultV1,
    "model_score_request_v1": ModelScoreRequestV1,
    "model_score_response_v1": ModelScoreResponseV1,
    "model_verify_artifact_request_v1": ModelVerifyArtifactRequestV1,
    "model_verify_artifact_response_v1": ModelVerifyArtifactResponseV1,
    "risk_input_v1": RiskInputV1,
    "risk_engine_config_v1": RiskEngineConfigV1,
    "risk_explanation_path_v1": RiskExplanationPathV1,
    "risk_contribution_v1": RiskContributionV1,
    "asset_risk_score_v1": AssetRiskScoreV1,
    "risk_projection_delta_v1": RiskProjectionDeltaV1,
    "risk_compute_request_v1": RiskComputeRequestV1,
    "risk_compute_response_v1": RiskComputeResponseV1,
    "risk_scores_list_response_v1": RiskScoresListResponseV1,
    "generation_request_v1": GenerationRequestV1,
    "generation_response_v1": GenerationResponseV1,
    "generation_artifact_v1": GenerationArtifactV1,
    "model_config_v1": ModelConfigV1,
    "provider_usage_v1": ProviderUsageV1,
    "provider_error_v1": ProviderErrorV1,
    "recorded_response_key_v1": RecordedResponseKeyV1,
    "provider_generate_request_v1": ProviderGenerateRequestV1,
    "provider_generate_response_v1": ProviderGenerateResponseV1,
    "provider_capabilities_v1": ProviderCapabilitiesV1,
    "structured_output_spec_v1": StructuredOutputSpecV1,
    "tool_schema_v1": ToolSchemaV1,
    "agent_definition_v1": AgentDefinitionV1,
    "agent_task_v1": AgentTaskV1,
    "agent_budget_v1": AgentBudgetV1,
    "agent_state_transition_v1": AgentStateTransitionV1,
    "tool_definition_v1": ToolDefinitionV1,
    "tool_invocation_v1": ToolInvocationV1,
    "tool_result_v1": ToolResultV1,
    "evidence_citation_v1": EvidenceCitationV1,
    "agent_artifact_v1": AgentArtifactV1,
    "create_agent_session_request_v1": CreateAgentSessionRequestV1,
    "create_agent_task_request_v1": CreateAgentTaskRequestV1,
    "agent_session_detail_v1": AgentSessionDetailV1,
    "watchtower_triage_result_v1": WatchtowerTriageResultV1,
    "trace_investigation_plan_v1": TraceInvestigationPlanV1,
    "evidence_attachment_v1": EvidenceAttachmentV1,
    "candidate_affected_asset_v1": CandidateAffectedAssetV1,
    "investigation_note_v1": InvestigationNoteV1,
    "agent_graph_overlay_v1": AgentGraphOverlayV1,
    "investigation_detail_v1": InvestigationDetailV1,
}
