"""Fixture name to contract model mapping for cross-language tests."""

from __future__ import annotations

from pydantic import BaseModel

from aegis_contracts.agent_runtime import (
    AgentArtifactV1,
    AgentBudgetV1,
    AgentDefinitionV1,
    AgentSessionDetailV1,
    AgentStateTransitionV1,
    AgentTaskV1,
    CreateAgentSessionRequestV1,
    CreateAgentTaskRequestV1,
    EvidenceCitationV1,
    ToolDefinitionV1,
    ToolInvocationV1,
    ToolResultV1,
)
from aegis_contracts.api import CursorPaginationV1, IdempotencyMetadataV1
from aegis_contracts.approvals import (
    ApproveProposalRequestV1,
    ApproveProposalResponseV1,
    AuthorizedSimulationCommandV1,
    CancelProposalRequestV1,
    CancelProposalResponseV1,
    ExecutionResultV1,
    FinalPolicyCheckV1,
    ModifyProposalRequestV1,
    ModifyProposalResponseV1,
    ProposalModificationV1,
    RejectProposalRequestV1,
    RejectProposalResponseV1,
    StaleProposalErrorV1,
)
from aegis_contracts.auth import (
    AuthenticatedActorV1,
    AuthorizationDecisionV1,
    PermissionContractV1,
    ResourceAccessGrantV1,
    RoleContractV1,
    SecurityAuditEventV1,
    SessionInfoV1,
)
from aegis_contracts.cinematic import (
    CameraDirectiveV1,
    CinematicBeatV1,
    CinematicChapterV1,
    CinematicPlanV1,
    CinematicPlaybackStateV1,
    CinematicProvenanceV1,
    PresentationHintV1,
)
from aegis_contracts.entities import (
    ActionProposalV1,
    AgentSessionV1,
    AlertV1,
    ApprovalV1,
    EvidenceV1,
    ExecutedActionV1,
    HypothesisV1,
    IncidentV1,
    ModelManifestV1,
    ModelScoreV1,
    RunV1,
    ScenarioV1,
    ScenarioVersionV1,
)
from aegis_contracts.errors import ApiErrorEnvelopeV1
from aegis_contracts.events import DomainEventEnvelopeV1
from aegis_contracts.features import (
    DatasetManifestV1,
    FeatureComputeRequestV1,
    FeatureComputeResponseV1,
    FeatureParityCheckResponseV1,
    FeatureSchemaManifestV1,
    FeatureVectorV1,
    FeatureWindowV1,
    OnlineFeatureUpdateV1,
)
from aegis_contracts.generation import (
    GenerationArtifactV1,
    GenerationRequestV1,
    GenerationResponseV1,
    ModelConfigV1,
    ProviderCapabilitiesV1,
    ProviderErrorV1,
    ProviderGenerateRequestV1,
    ProviderGenerateResponseV1,
    ProviderUsageV1,
    RecordedResponseKeyV1,
    StructuredOutputSpecV1,
    ToolSchemaV1,
)
from aegis_contracts.graph import (
    GraphDeltaV1,
    GraphEdgeV1,
    GraphNodeV1,
    GraphPathQueryV1,
    GraphPathResultV1,
    GraphSnapshotV1,
)
from aegis_contracts.investigation import (
    AgentGraphOverlayV1,
    CandidateAffectedAssetV1,
    EvidenceAttachmentV1,
    InvestigationDetailV1,
    InvestigationNoteV1,
    TraceInvestigationPlanV1,
    WatchtowerTriageResultV1,
)
from aegis_contracts.live_run import (
    ConnectionHealthSnapshotV1,
    RunCommandResponseV1,
    RunCreateRequestV1,
    RunReplicatedState,
    SnapshotBootstrapPayloadV1,
    TimelineEntryV1,
)
from aegis_contracts.models import (
    AnomalyExplanationV1,
    ModelArtifactReferenceV1,
    ModelInferenceResultV1,
    ModelScoreRequestV1,
    ModelScoreResponseV1,
    ModelVerifyArtifactRequestV1,
    ModelVerifyArtifactResponseV1,
    TrainingRunManifestV1,
)
from aegis_contracts.observability import (
    DependencyStatusV1,
    HealthResponseV1,
    MetricLabelPolicyV1,
    ReadyResponseV1,
    StructuredLogRecordV1,
    TelemetryContextV1,
)
from aegis_contracts.persistence import IdempotencyRecordV1, ObjectMetadataReferenceV1
from aegis_contracts.proposals import (
    ApprovalRequirementV1,
    PolicyDecisionV1,
    PolicyInputV1,
    ProposalRevisionV1,
    ResponseOptionV1,
    TriggerBastionRequestV1,
    TriggerWardenRequestV1,
)
from aegis_contracts.realtime import (
    BackfillRequestV1,
    BackfillResultV1,
    ConsumerCursorV1,
    DeadLetterRecordV1,
    RealtimeMessageEnvelopeV1,
)
from aegis_contracts.replay import (
    ReplayCursorRangeV1,
    ReplayCursorV1,
    ReplayEquivalenceResultV1,
    ReplayProvenanceV1,
    ReplaySnapshotV1,
    ReplayStateV1,
    SnapshotManifestV1,
    StateDiffV1,
)
from aegis_contracts.replay_frontend import (
    HistoricalGraphAdapterV1,
    ReplayBookmarkV1,
    ReplayComparisonV1,
    ReplayViewStateV1,
    ReturnToLiveResultV1,
    TimelineFilterV1,
)
from aegis_contracts.reports import (
    AfterActionReportSourceV1,
    AfterActionReportV1,
    GroundingValidationResultV1,
    ReportCitationV1,
    ReportClaimV1,
    ReportExportArtifactV1,
    ReportTimelineEntryV1,
    ReportVersionV1,
    TriggerScribeRequestV1,
)
from aegis_contracts.risk import (
    AssetRiskScoreV1,
    RiskComputeRequestV1,
    RiskComputeResponseV1,
    RiskContributionV1,
    RiskEngineConfigV1,
    RiskExplanationPathV1,
    RiskInputV1,
    RiskProjectionDeltaV1,
    RiskScoresListResponseV1,
)
from aegis_contracts.scoring import (
    AfterActionViewModelV1,
    DecisionReviewV1,
    MissedEvidenceItemV1,
    RunComparisonV1,
    RunScoreV1,
    ScoreComponentV1,
    ScoreExplanationV1,
    ScoreExportArtifactV1,
    ScoreProvenanceV1,
    ScoreRubricV1,
    ValidAlternativeV1,
)
from aegis_contracts.simulation import (
    NormalizedEventHashV1,
    RunConfigurationV1,
    ScheduledEventV1,
    SimulationCheckpointV1,
    SimulationCommandV1,
    WorldStateSnapshotV1,
)
from aegis_contracts.websocket import WebSocketFrameV1

FIXTURE_MODEL_MAP: dict[str, type[BaseModel]] = {
    "event_envelope_v1": DomainEventEnvelopeV1,
    "graph_node_v1": GraphNodeV1,
    "graph_edge_v1": GraphEdgeV1,
    "graph_snapshot_v1": GraphSnapshotV1,
    "graph_delta_v1": GraphDeltaV1,
    "graph_path_query_v1": GraphPathQueryV1,
    "graph_path_result_v1": GraphPathResultV1,
    "api_error_v1": ApiErrorEnvelopeV1,
    "cursor_page_v1": CursorPaginationV1,
    "idempotency_v1": IdempotencyMetadataV1,
    "idempotency_record_v1": IdempotencyRecordV1,
    "object_metadata_reference_v1": ObjectMetadataReferenceV1,
    "scenario_v1": ScenarioV1,
    "scenario_version_v1": ScenarioVersionV1,
    "run_v1": RunV1,
    "alert_v1": AlertV1,
    "incident_v1": IncidentV1,
    "evidence_v1": EvidenceV1,
    "hypothesis_v1": HypothesisV1,
    "agent_session_v1": AgentSessionV1,
    "action_proposal_v1": ActionProposalV1,
    "approval_v1": ApprovalV1,
    "executed_action_v1": ExecutedActionV1,
    "model_manifest_v1": ModelManifestV1,
    "model_score_v1": ModelScoreV1,
    "run_configuration_v1": RunConfigurationV1,
    "scheduled_event_v1": ScheduledEventV1,
    "simulation_command_v1": SimulationCommandV1,
    "simulation_checkpoint_v1": SimulationCheckpointV1,
    "world_state_snapshot_v1": WorldStateSnapshotV1,
    "normalized_event_hash_v1": NormalizedEventHashV1,
    "realtime_message_envelope_v1": RealtimeMessageEnvelopeV1,
    "consumer_cursor_v1": ConsumerCursorV1,
    "dead_letter_record_v1": DeadLetterRecordV1,
    "backfill_request_v1": BackfillRequestV1,
    "backfill_result_v1": BackfillResultV1,
    "websocket_frame_v1": WebSocketFrameV1,
    "live_run_v1": RunReplicatedState,
    "timeline_entry_v1": TimelineEntryV1,
    "snapshot_bootstrap_v1": SnapshotBootstrapPayloadV1,
    "run_create_request_v1": RunCreateRequestV1,
    "run_command_response_v1": RunCommandResponseV1,
    "connection_health_v1": ConnectionHealthSnapshotV1,
    "feature_schema_manifest_v1": FeatureSchemaManifestV1,
    "feature_vector_v1": FeatureVectorV1,
    "feature_window_v1": FeatureWindowV1,
    "dataset_manifest_v1": DatasetManifestV1,
    "online_feature_update_v1": OnlineFeatureUpdateV1,
    "feature_compute_request_v1": FeatureComputeRequestV1,
    "feature_compute_response_v1": FeatureComputeResponseV1,
    "feature_parity_check_response_v1": FeatureParityCheckResponseV1,
    "anomaly_explanation_v1": AnomalyExplanationV1,
    "training_run_manifest_v1": TrainingRunManifestV1,
    "model_artifact_reference_v1": ModelArtifactReferenceV1,
    "model_inference_result_v1": ModelInferenceResultV1,
    "model_score_request_v1": ModelScoreRequestV1,
    "model_score_response_v1": ModelScoreResponseV1,
    "model_verify_artifact_request_v1": ModelVerifyArtifactRequestV1,
    "model_verify_artifact_response_v1": ModelVerifyArtifactResponseV1,
    "risk_input_v1": RiskInputV1,
    "risk_engine_config_v1": RiskEngineConfigV1,
    "risk_explanation_path_v1": RiskExplanationPathV1,
    "risk_contribution_v1": RiskContributionV1,
    "asset_risk_score_v1": AssetRiskScoreV1,
    "risk_projection_delta_v1": RiskProjectionDeltaV1,
    "risk_compute_request_v1": RiskComputeRequestV1,
    "risk_compute_response_v1": RiskComputeResponseV1,
    "risk_scores_list_response_v1": RiskScoresListResponseV1,
    "generation_request_v1": GenerationRequestV1,
    "generation_response_v1": GenerationResponseV1,
    "generation_artifact_v1": GenerationArtifactV1,
    "model_config_v1": ModelConfigV1,
    "provider_usage_v1": ProviderUsageV1,
    "provider_error_v1": ProviderErrorV1,
    "recorded_response_key_v1": RecordedResponseKeyV1,
    "provider_generate_request_v1": ProviderGenerateRequestV1,
    "provider_generate_response_v1": ProviderGenerateResponseV1,
    "provider_capabilities_v1": ProviderCapabilitiesV1,
    "structured_output_spec_v1": StructuredOutputSpecV1,
    "tool_schema_v1": ToolSchemaV1,
    "agent_definition_v1": AgentDefinitionV1,
    "agent_task_v1": AgentTaskV1,
    "agent_budget_v1": AgentBudgetV1,
    "agent_state_transition_v1": AgentStateTransitionV1,
    "tool_definition_v1": ToolDefinitionV1,
    "tool_invocation_v1": ToolInvocationV1,
    "tool_result_v1": ToolResultV1,
    "evidence_citation_v1": EvidenceCitationV1,
    "agent_artifact_v1": AgentArtifactV1,
    "create_agent_session_request_v1": CreateAgentSessionRequestV1,
    "create_agent_task_request_v1": CreateAgentTaskRequestV1,
    "agent_session_detail_v1": AgentSessionDetailV1,
    "watchtower_triage_result_v1": WatchtowerTriageResultV1,
    "trace_investigation_plan_v1": TraceInvestigationPlanV1,
    "evidence_attachment_v1": EvidenceAttachmentV1,
    "candidate_affected_asset_v1": CandidateAffectedAssetV1,
    "investigation_note_v1": InvestigationNoteV1,
    "agent_graph_overlay_v1": AgentGraphOverlayV1,
    "investigation_detail_v1": InvestigationDetailV1,
    "response_option_v1": ResponseOptionV1,
    "proposal_revision_v1": ProposalRevisionV1,
    "approval_requirement_v1": ApprovalRequirementV1,
    "policy_input_v1": PolicyInputV1,
    "policy_decision_v1": PolicyDecisionV1,
    "trigger_bastion_request_v1": TriggerBastionRequestV1,
    "trigger_warden_request_v1": TriggerWardenRequestV1,
    "report_citation_v1": ReportCitationV1,
    "report_claim_v1": ReportClaimV1,
    "report_timeline_entry_v1": ReportTimelineEntryV1,
    "after_action_report_source_v1": AfterActionReportSourceV1,
    "after_action_report_v1": AfterActionReportV1,
    "report_version_v1": ReportVersionV1,
    "report_export_artifact_v1": ReportExportArtifactV1,
    "grounding_validation_result_v1": GroundingValidationResultV1,
    "trigger_scribe_request_v1": TriggerScribeRequestV1,
    "stale_proposal_error_v1": StaleProposalErrorV1,
    "proposal_modification_v1": ProposalModificationV1,
    "final_policy_check_v1": FinalPolicyCheckV1,
    "authorized_simulation_command_v1": AuthorizedSimulationCommandV1,
    "execution_result_v1": ExecutionResultV1,
    "approve_proposal_request_v1": ApproveProposalRequestV1,
    "reject_proposal_request_v1": RejectProposalRequestV1,
    "modify_proposal_request_v1": ModifyProposalRequestV1,
    "cancel_proposal_request_v1": CancelProposalRequestV1,
    "approve_proposal_response_v1": ApproveProposalResponseV1,
    "reject_proposal_response_v1": RejectProposalResponseV1,
    "modify_proposal_response_v1": ModifyProposalResponseV1,
    "cancel_proposal_response_v1": CancelProposalResponseV1,
    "replay_cursor_v1": ReplayCursorV1,
    "replay_cursor_range_v1": ReplayCursorRangeV1,
    "replay_provenance_v1": ReplayProvenanceV1,
    "replay_state_v1": ReplayStateV1,
    "replay_snapshot_v1": ReplaySnapshotV1,
    "snapshot_manifest_v1": SnapshotManifestV1,
    "state_diff_v1": StateDiffV1,
    "replay_equivalence_result_v1": ReplayEquivalenceResultV1,
    "replay_view_state_v1": ReplayViewStateV1,
    "replay_bookmark_v1": ReplayBookmarkV1,
    "replay_comparison_v1": ReplayComparisonV1,
    "timeline_filter_v1": TimelineFilterV1,
    "historical_graph_adapter_v1": HistoricalGraphAdapterV1,
    "return_to_live_result_v1": ReturnToLiveResultV1,
    "cinematic_provenance_v1": CinematicProvenanceV1,
    "camera_directive_v1": CameraDirectiveV1,
    "cinematic_beat_v1": CinematicBeatV1,
    "cinematic_chapter_v1": CinematicChapterV1,
    "presentation_hint_v1": PresentationHintV1,
    "cinematic_playback_state_v1": CinematicPlaybackStateV1,
    "cinematic_plan_v1": CinematicPlanV1,
    "score_explanation_v1": ScoreExplanationV1,
    "score_rubric_v1": ScoreRubricV1,
    "score_component_v1": ScoreComponentV1,
    "score_provenance_v1": ScoreProvenanceV1,
    "decision_review_v1": DecisionReviewV1,
    "missed_evidence_item_v1": MissedEvidenceItemV1,
    "valid_alternative_v1": ValidAlternativeV1,
    "run_score_v1": RunScoreV1,
    "after_action_view_model_v1": AfterActionViewModelV1,
    "run_comparison_v1": RunComparisonV1,
    "score_export_artifact_v1": ScoreExportArtifactV1,
    "authenticated_actor_v1": AuthenticatedActorV1,
    "role_v1": RoleContractV1,
    "permission_v1": PermissionContractV1,
    "resource_access_grant_v1": ResourceAccessGrantV1,
    "authorization_decision_v1": AuthorizationDecisionV1,
    "session_info_v1": SessionInfoV1,
    "security_audit_event_v1": SecurityAuditEventV1,
    "telemetry_context_v1": TelemetryContextV1,
    "structured_log_record_v1": StructuredLogRecordV1,
    "health_response_v1": HealthResponseV1,
    "ready_response_v1": ReadyResponseV1,
    "dependency_status_v1": DependencyStatusV1,
    "metric_label_policy_v1": MetricLabelPolicyV1,
}
